contentdir = "content"
layoutdir = "layouts"
publishdir = "public"
builddrafts = false
baseurl = "http://zhaojames0707.github.io/"
languageCode = "zh-CN"
title = "Mission Namek"
paginate = 10
Copyright = "All rights reserved - 2016"
disqusShortname = "missionnamek"

[params]
  description = "We live and die by your order, Boss!"
  cover = "images/code.jpg"
  author = "James Zhao"
  authorlocation = "Beijing, China"
  authorwebsite = "http://zhaojames0707.github.com"
  bio = "Python developer"
  logo = "images/logo.jpeg"
  githubName = "zhaojames0707"

[[menu.main]]
  name = "Blog"
  weight = -120
  identifier = "blog"
  url = "/"

[[menu.main]]
  name = "About me"
  weight = -110
  identifier = "about"
  url = "/about"

[[menu.main]]
  name = "Github repos"
  weight = 100
  pre = "<h3>Follow me</h3>"
  url = "https://github.com/zhaojames0707"
